Bb Jarrah, [7/17/2025 7:30 PM]
title: "Banan Aljarrah"
description: "Clinical Pharmacy Student | R for Health Data | Data Storytelling"
theme: jekyll-theme-minimal
show_downloads: false
github:
  is_project_page: false


![Alt text for screen readers](assets/images/your-6.jpg)
